/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuppressionDesDonneesRouteImport } from './routes/suppression-des-donnees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAuditsAuditIdRouteImport } from './routes/_authenticated/audits.$auditId'
import { Route as AuthenticatedStoresIndexRouteImport } from './routes/_authenticated/stores.index'
import { Route as AuthenticatedStoresStoreIdRouteImport } from './routes/_authenticated/stores.$storeId'
import { Route as AuthenticatedTrackingStoreIdRouteImport } from './routes/_authenticated/tracking.$storeId'
import { Route as ApiInternalJobsTickRouteImport } from './routes/api/internal/jobs/tick'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicOauthGoogleCallbackRouteImport } from './routes/api/public/oauth/google/callback'
import { Route as ApiPublicOauthMetaCallbackRouteImport } from './routes/api/public/oauth/meta/callback'
import { Route as ApiPublicOauthShopifyCallbackRouteImport } from './routes/api/public/oauth/shopify/callback'
import { Route as ApiPublicWebhooksShopifyTopicRouteImport } from './routes/api/public/webhooks/shopify/$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppressionDesDonneesRoute = SuppressionDesDonneesRouteImport.update({
  id: '/suppression-des-donnees',
  path: '/suppression-des-donnees',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsAuditIdRoute =
  AuthenticatedAuditsAuditIdRouteImport.update({
    id: '/audits/$auditId',
    path: '/audits/$auditId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresIndexRoute =
  AuthenticatedStoresIndexRouteImport.update({
    id: '/stores/',
    path: '/stores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoresStoreIdRoute =
  AuthenticatedStoresStoreIdRouteImport.update({
    id: '/stores/$storeId',
    path: '/stores/$storeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackingStoreIdRoute =
  AuthenticatedTrackingStoreIdRouteImport.update({
    id: '/tracking/$storeId',
    path: '/tracking/$storeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiInternalJobsTickRoute = ApiInternalJobsTickRouteImport.update({
  id: '/api/internal/jobs/tick',
  path: '/api/internal/jobs/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthGoogleCallbackRoute =
  ApiPublicOauthGoogleCallbackRouteImport.update({
    id: '/api/public/oauth/google/callback',
    path: '/api/public/oauth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthMetaCallbackRoute =
  ApiPublicOauthMetaCallbackRouteImport.update({
    id: '/api/public/oauth/meta/callback',
    path: '/api/public/oauth/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthShopifyCallbackRoute =
  ApiPublicOauthShopifyCallbackRouteImport.update({
    id: '/api/public/oauth/shopify/callback',
    path: '/api/public/oauth/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksShopifyTopicRoute =
  ApiPublicWebhooksShopifyTopicRouteImport.update({
    id: '/api/public/webhooks/shopify/$topic',
    path: '/api/public/webhooks/shopify/$topic',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppression-des-donnees': typeof SuppressionDesDonneesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/tracking/$storeId': typeof AuthenticatedTrackingStoreIdRoute
  '/stores/': typeof AuthenticatedStoresIndexRoute
  '/api/internal/jobs/tick': typeof ApiInternalJobsTickRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/shopify/callback': typeof ApiPublicOauthShopifyCallbackRoute
  '/api/public/webhooks/shopify/$topic': typeof ApiPublicWebhooksShopifyTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppression-des-donnees': typeof SuppressionDesDonneesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/tracking/$storeId': typeof AuthenticatedTrackingStoreIdRoute
  '/stores': typeof AuthenticatedStoresIndexRoute
  '/api/internal/jobs/tick': typeof ApiInternalJobsTickRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/shopify/callback': typeof ApiPublicOauthShopifyCallbackRoute
  '/api/public/webhooks/shopify/$topic': typeof ApiPublicWebhooksShopifyTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppression-des-donnees': typeof SuppressionDesDonneesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/_authenticated/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/_authenticated/tracking/$storeId': typeof AuthenticatedTrackingStoreIdRoute
  '/_authenticated/stores/': typeof AuthenticatedStoresIndexRoute
  '/api/internal/jobs/tick': typeof ApiInternalJobsTickRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/oauth/google/callback': typeof ApiPublicOauthGoogleCallbackRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/shopify/callback': typeof ApiPublicOauthShopifyCallbackRoute
  '/api/public/webhooks/shopify/$topic': typeof ApiPublicWebhooksShopifyTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/sitemap.xml'
    | '/suppression-des-donnees'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/audits/$auditId'
    | '/stores/$storeId'
    | '/tracking/$storeId'
    | '/stores/'
    | '/api/internal/jobs/tick'
    | '/api/public/webhooks/stripe'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/shopify/callback'
    | '/api/public/webhooks/shopify/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confidentialite'
    | '/sitemap.xml'
    | '/suppression-des-donnees'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/audits/$auditId'
    | '/stores/$storeId'
    | '/tracking/$storeId'
    | '/stores'
    | '/api/internal/jobs/tick'
    | '/api/public/webhooks/stripe'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/shopify/callback'
    | '/api/public/webhooks/shopify/$topic'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confidentialite'
    | '/sitemap.xml'
    | '/suppression-des-donnees'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/audits/$auditId'
    | '/_authenticated/stores/$storeId'
    | '/_authenticated/tracking/$storeId'
    | '/_authenticated/stores/'
    | '/api/internal/jobs/tick'
    | '/api/public/webhooks/stripe'
    | '/api/public/oauth/google/callback'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/shopify/callback'
    | '/api/public/webhooks/shopify/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuppressionDesDonneesRoute: typeof SuppressionDesDonneesRoute
  ApiInternalJobsTickRoute: typeof ApiInternalJobsTickRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicOauthGoogleCallbackRoute: typeof ApiPublicOauthGoogleCallbackRoute
  ApiPublicOauthMetaCallbackRoute: typeof ApiPublicOauthMetaCallbackRoute
  ApiPublicOauthShopifyCallbackRoute: typeof ApiPublicOauthShopifyCallbackRoute
  ApiPublicWebhooksShopifyTopicRoute: typeof ApiPublicWebhooksShopifyTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppression-des-donnees': {
      id: '/suppression-des-donnees'
      path: '/suppression-des-donnees'
      fullPath: '/suppression-des-donnees'
      preLoaderRoute: typeof SuppressionDesDonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits/$auditId': {
      id: '/_authenticated/audits/$auditId'
      path: '/audits/$auditId'
      fullPath: '/audits/$auditId'
      preLoaderRoute: typeof AuthenticatedAuditsAuditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/': {
      id: '/_authenticated/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof AuthenticatedStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores/$storeId': {
      id: '/_authenticated/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracking/$storeId': {
      id: '/_authenticated/tracking/$storeId'
      path: '/tracking/$storeId'
      fullPath: '/tracking/$storeId'
      preLoaderRoute: typeof AuthenticatedTrackingStoreIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/internal/jobs/tick': {
      id: '/api/internal/jobs/tick'
      path: '/api/internal/jobs/tick'
      fullPath: '/api/internal/jobs/tick'
      preLoaderRoute: typeof ApiInternalJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/google/callback': {
      id: '/api/public/oauth/google/callback'
      path: '/api/public/oauth/google/callback'
      fullPath: '/api/public/oauth/google/callback'
      preLoaderRoute: typeof ApiPublicOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta/callback': {
      id: '/api/public/oauth/meta/callback'
      path: '/api/public/oauth/meta/callback'
      fullPath: '/api/public/oauth/meta/callback'
      preLoaderRoute: typeof ApiPublicOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/shopify/callback': {
      id: '/api/public/oauth/shopify/callback'
      path: '/api/public/oauth/shopify/callback'
      fullPath: '/api/public/oauth/shopify/callback'
      preLoaderRoute: typeof ApiPublicOauthShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shopify/$topic': {
      id: '/api/public/webhooks/shopify/$topic'
      path: '/api/public/webhooks/shopify/$topic'
      fullPath: '/api/public/webhooks/shopify/$topic'
      preLoaderRoute: typeof ApiPublicWebhooksShopifyTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAuditsAuditIdRoute: typeof AuthenticatedAuditsAuditIdRoute
  AuthenticatedStoresStoreIdRoute: typeof AuthenticatedStoresStoreIdRoute
  AuthenticatedTrackingStoreIdRoute: typeof AuthenticatedTrackingStoreIdRoute
  AuthenticatedStoresIndexRoute: typeof AuthenticatedStoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAuditsAuditIdRoute: AuthenticatedAuditsAuditIdRoute,
  AuthenticatedStoresStoreIdRoute: AuthenticatedStoresStoreIdRoute,
  AuthenticatedTrackingStoreIdRoute: AuthenticatedTrackingStoreIdRoute,
  AuthenticatedStoresIndexRoute: AuthenticatedStoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuppressionDesDonneesRoute: SuppressionDesDonneesRoute,
  ApiInternalJobsTickRoute: ApiInternalJobsTickRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicOauthGoogleCallbackRoute: ApiPublicOauthGoogleCallbackRoute,
  ApiPublicOauthMetaCallbackRoute: ApiPublicOauthMetaCallbackRoute,
  ApiPublicOauthShopifyCallbackRoute: ApiPublicOauthShopifyCallbackRoute,
  ApiPublicWebhooksShopifyTopicRoute: ApiPublicWebhooksShopifyTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
